### ISSUE TITLE
Error fetching random unwatched movie: 400 Client Error

### ISSUE THREAD

**Issue by dannycab** [sahara101/Movie-Roulette#6]
I spun up this docker image and it seems to work well. It finds my AppleTVs, connects to trakt and overseer. But the request to jellyfin go unmet.

Here I am replacing my DOMAIN and USERNAME with the error:

```
movie-roulette  | ERROR:utils.jellyfin_service:Error fetching random unwatched movie: 400 Client Error: Bad Request for url: https://DOMAIN/Users/USERNAME/Items?IncludeItemTypes=Movie&Recursive=true&SortBy=Random&Limit=1&Fields=Overview%2CPeople%2CGenres%2CCommunityRating%2CRunTimeTicks%2CProviderIds%2CUserData%2COfficialRating&IsPlayed=false
movie-roulette  | INFO:utils.jellyfin_service:Jellyfin cache update completed
```

I'm not sure if I've set up the connection to Jellyfin correctly, or if there's some other issue. Here's the docker compose that I'm using:

```
services:
  movie-roulette:
    image: ghcr.io/sahara101/movie-roulette:latest
    container_name: movie-roulette
    network_mode: host
    environment:
      - TZ=America/Detroit
      - JELLYFIN_URL=DOMAIN_1
      - JELLYFIN_API_KEY=KEY_1
      - JELLYFIN_USER_ID=USER
      - OVERSEERR_URL=DOMAIN_2
      - OVERSEERR_API_KEY=KEY_2
      - APPLE_TV_ID=ID_FROM_APPLE_TV
    volumes:
      - /srv/docker-services/movie-roulette/data:/app/data
    restart: unless-stopped
    ```
